version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing dependencies..
      - yum install maven -y
      - mvn -version

  pre_build:
    commands:
      - echo Compiling source code...
      - mvn clean
      - aws s3 cp https://github.com/AWS-Trainees-Practice/maven-web-application-2.git s3://phone123/qwerty/

  build:
    commands:
      - echo Running unit tests...
      - mvn test

  post_build:
    commands:
      - echo Packaging the application...
      - mvn package

artifacts:
  files:
    - target/my-application.war
